### ISSUE TITLE
how to run this program

### ISSUE THREAD

**Issue by shengbintai** [nhynes/chisel3-axi#1]
Hello, how to run this program？

**Comment by nhynes** [comment]
It's a library, so you'll want to include `"edu.berkeley.cs" %% "chisel3-axi" % "0.1.0-SNAPSHOT"` in your `libraryDepednenncies`. Then you can use some of the classes in your `io`. For instance,

```scala
  val io = IO(new Bundle {
    val ctrl = AxiLiteSlave(log2Ceil(NumCtrlRegs * CtrlBusBytes), CtrlBusWidth)
    val m = AxiMaster(dmaAddrWidth, dmaDataWidth)
    val sm = AxiStreamMaster(dmaDataWidth)
    val ss = AxiStreamSlave(dmaDataWidth)
  })

  // these will assign the AXI default values to the optional signals
  io.m.initDefault
  io.sm.bits.initDefault
```

You can connect up the other inputs/outputs as per usual.

**Comment by NikolaosGian** [comment]
I have attached the libraryDepednenncies in my file but getting this result you know how to resolve it?
my build.sbt file:

```
scalaVersion := "2.12.15"

scalacOptions ++= Seq(
  "-deprecation",
  "-feature",
  "-unchecked",
  "-Xfatal-warnings",
  "-language:reflectiveCalls",
)

// Chisel 3.5
addCompilerPlugin("edu.berkeley.cs" % "chisel3-plugin" % "3.5.3" cross CrossVersion.full)
libraryDependencies += "edu.berkeley.cs" %% "chisel3" % "3.5.3"
libraryDependencies += "edu.berkeley.cs" %% "chiseltest" % "0.5.3"
libraryDependencies += "edu.berkeley.cs" %% "chisel3-axi" % "0.1.0-SNAPSHOT"
```




Error:
```

[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:chisel3-axi_2.12:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/hardwaredesign/.ivy2/localedu.berkeley.cs/chisel3-axi_2.12/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   download error: Caught java.net.UnknownHostException (repo1.maven.org) while downloading https://repo1.maven.org/maven2/edu/berkeley/cs/chisel3-axi_2.12/0.1.0-SNAPSHOT/chisel3-axi_2.12-0.1.0-SNAPSHOT.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:60)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:134)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:147)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:147)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:128)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:161)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:chisel3-axi_2.12:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /home/hardwaredesign/.ivy2/localedu.berkeley.cs/chisel3-axi_2.12/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   download error: Caught java.net.UnknownHostException (repo1.maven.org) while downloading https://repo1.maven.org/maven2/edu/berkeley/cs/chisel3-axi_2.12/0.1.0-SNAPSHOT/chisel3-axi_2.12-0.1.0-SNAPSHOT.pom
[error] Total time: 1 s, completed Jan 18, 2024, 9:19:50 AM

```
